[[plugins]]
repo = "Shougo/denite.nvim"

[[plugins]]
repo = "cocopon/iceberg.vim"
hook_add = "colorscheme iceberg"

[[plugins]]
repo = "scrooloose/nerdtree"

[[plugins]]
repo = "tiagofumo/vim-nerdtree-syntax-highlight"

[[plugins]]
repo = "Shougo/deoplete.nvim"

[[plugins]]
repo = "vim-airline/vim-airline"

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "zchee/deoplete-jedi"

[[plugins]]
repo = "davidhalter/jedi-vim"

[[plugins]]
repo = "w0rp/ale"

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ["c", "cc", "cpp", "h", "hh", "hpp", "cmake"]
depends = ['deoplete.nvim']
hook_source = '''
let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-6.0/lib/libclang-6.0.so.1'
let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
'''

[[plugins]]
repo = "tweekmonster/impsort.vim"

[[plugins]]
repo = "nathanaelkane/vim-indent-guides"

[[plugins]]
repo = "cohama/lexima.vim"

[[plugins]]
repo = "bronson/vim-trailing-whitespace"

[[plugins]]
repo = "tpope/vim-commentary"

[[plugins]]
repo = "vim-python/python-syntax"

[[plugins]]
repo = "nvie/vim-flake8"

[[plugins]]
repo = "octol/vim-cpp-enhanced-highlight"

[[plugins]]
repo = "vim-jp/cpp-vim"
